Source extensions
avdstaaij/cpp-init pull request #4
Opened 2020-11-25 09:36 UTC by Thyrum

This pull would add support for multiple file extensions. Multiple exenstions can be provided using `SRCEXT ::= .cpp .cc`, that is, a space seperated list.

2020-11-25 15:05 UTC, avdstaaij requested changes
I have tested the new Makefile and it works perfectly!
I have not tested the version check, but the implementation looks very clean and the source seems trustable.

In the additions, you have written all new variables in lowercase. All existing variables are in uppercase, so this is a bit of clash. I recommend making the new variables uppercase as well. The `compile_rule` is a very different type of object, so I think keeping that lowercase is fine. Since it encompasses two rules, it may be more accurate to call it `compile_rules`, but the singular form is fine as well.

If you are going to apply my proposed changes, I suggest you amend the first commit via interactive rebase to keep the history clean.

The readme still needs to be amended before merging. (FIXED)

The second commit title should read `>=` instead of `>`. (FIXED)

2020-11-25 15:05 UTC, avdstaaij commented on Makefile
> +         $(foreach ext, $(SRCEXT), $(patsubst $(SRCDIR)/%$(ext),$(DEPDIR_D)/%.d,$(filter %$(ext), $(SOURCES))))
These lines are now over 80 characters long, which is not preferred.
However, I do not see an easy way to shorten them, so it is acceptable.
If you know a way to shorten them that does not hinder readability, you are of course encouraged to do so.

2020-11-25 15:24 UTC, Thyrum commented
My reasoning for using lower case variable names was that these are local variables. I find it helpful to distinguish between the scope of variables in such a manner (I have also done this on other pull requests if I recall correctly).
The variable `has_features` however should definitely be upper case.

2020-11-25 18:39 UTC, avdstaaij commented
> My reasoning for using lower case variable names was that these are "local"/"scoped" variables. I find it helpful to distinguish between the scope of variables in such a manner (I have also done this on other pull requests if I recall correctly).
> The variable `has_features` however should definitely be upper case.

That makes sense.

2020-12-01 23:38 UTC, avdstaaij commented
I have added this PR's feature to the readme and fixed the `>`/`>=` mixup.

2020-12-03 10:46 UTC, avdstaaij commented
This branch now needs to be rebased on `master`. @Thyrum, you would probably do this best.

2020-12-23 09:55 UTC, Thyrum commented
As discussed in #1, the code complication is not worth the added functionality.

2020-12-23 09:55 UTC, closed without merging